version: '3.8'

services:
 app:
  build: ./backend
  working_dir: /server
  volumes:
   - ./backend:/server
   - /server/node_modules
  command: nodemon index.js
  ports: 
   - "8080:8080"
  environment:
   - URI=mongodb://mongo:27017/chats
  depends_on:
   - mongo

 mongo:
  image: mongo:latest
  ports:
   - "27017:27017"
  volumes:
   - mongo-data:/data/db

 frontend: 
  build: ./frontend
  working_dir: /ui
  volumes:
   - ./frontend:/ui
   - /ui/node_modules
  command: npm run dev -- --host
  ports: 
   - "5173:5173"
  depends_on: 
   - app

volumes:
 mongo-data:



